### PR TITLE
update recipe

### PR DESCRIPTION
**Pull request by ocefpaf**
@conda-forge-admin, please rerender

### CODE REVIEW

**Comment by ocefpaf** [comment]
`Environment: CONFIG=win_c_compilervs2008vc9, CONDA_INSTALL_LOCN=C:\Miniconda36-x64` is failing with:


```
C:\bld\xz_1532381842719\_build_env) C:\bld\xz_1532381842719\work>cmake -G "NMake Makefiles"       -DCMAKE_INSTALL_PREFIX="C:\bld\xz_1532381842719\_h_env\Library"       -DCMAKE_C_COMPILER=c99-to-c89-cmake-nmake-wrap.bat       -DCMAKE_C_USE_RESPONSE_FILE_FOR_OBJECTS:BOOL=FALSE       -DCMAKE_BUILD_TYPE=Release       --debug-trycompile       . 
debug trycompile on
-- The C compiler identification is unknown
CMake Error at CMakeLists.txt:3 (project):
  The CMAKE_C_COMPILER:
    c99-to-c89-cmake-nmake-wrap.bat
  is not a full path and was not found in the PATH.
  To use the NMake generator with Visual C++, cmake must be run from a shell
  that can use the compiler cl from the command line.  This environment is
  unable to invoke the cl compiler.  To fix this problem, run cmake from the
  Visual Studio Command Prompt (vcvarsall.bat).
  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.
-- Configuring incomplete, errors occurred!
See also "C:/bld/xz_1532381842719/work/CMakeFiles/CMakeOutput.log".
See also "C:/bld/xz_1532381842719/work/CMakeFiles/CMakeError.log".
(C:\bld\xz_1532381842719\_build_env) C:\bld\xz_1532381842719\work>nmake VERBOSE=1 
```

@isuruf do you have an idea if I'm doing something wrong here? Any advice?

**Comment by isuruf** [comment]
Anaconda has forked https://github.com/AnacondaRecipes/c99-to-c89 and the defaults recipe is for the fork. I haven't seen any PRs or issues upstream about sending those patches upstream

**Comment by mingwandroid** [comment]
c99-to-c89 is completely dead. I have no intention of attempting to upstream patches to a dead project.

Edit: Or do you mean upstream as in conda-forge?

**Comment by isuruf** [comment]
Ok, then we can point to your fork. Do you mind putting out a release in your fork so that we can package it?

**Comment by mingwandroid** [comment]
Yes, I need to figure out how again first!

**Comment by mingwandroid** [comment]
https://github.com/AnacondaRecipes/c99-to-c89/releases/tag/release-1.0.4

**Comment by ocefpaf** [comment]
Thanks @mingwandroid!

@isuruf I can take care of updating our `c99-to-c89`, don't worry about it.

**Pull request merged**
