### PR TITLE
fix tests

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by isuruf** [comment]
@ocefpaf, do you want to merge this with tests failing on windows, so that there are no more accidental broken uploads on windows?

**Comment by ocefpaf** [comment]
> @ocefpaf, do you want to merge this with tests failing on windows, so that there are no more accidental broken uploads on windows?

Argh. Completely forgot about this one. I'm not sure what you mean there. The failing test is:

```
if not exist %PREFIX%\Library\bin\liblzma.dll
```

Was that renamed? Removed? Can we just remove that test?

**Comment by isuruf** [comment]
> Was that renamed? Removed? Can we just remove that test?

You switched the build system in 5.2.9 and this file is missing due to that change.

**Comment by ocefpaf** [comment]
> You switched the build system in 5.2.9 and this file is missing due to that change.

Ah! Now I remember. I don't recall why I changed though :-)

**Comment by isuruf** [comment]
Why was this closed?

**Comment by xhochy** [comment]
I thought it was stale and I am also integrated similar changes in my update PR.

**Comment by xhochy** [comment]
> > @ocefpaf, do you want to merge this with tests failing on windows, so that there are no more accidental broken uploads on windows?
> 
> 
> 
> Argh. Completely forgot about this one. I'm not sure what you mean there. The failing test is:
> 
> 
> 
> ```
> 
> if not exist %PREFIX%\Library\bin\liblzma.dll
> 
> ```
> 
> 
> 
> Was that renamed? Removed? Can we just remove that test?

This should probably be in the updated build, right?

**Comment by xhochy** [comment]
This should be addressed in #42 where we build shared and static versions with CMake separately.

**Comment by ocefpaf** [comment]
@xhochy, sorry, late to respond here. I see you got it in #42. Thanks!

**Pull request closed without merging**
