### PR TITLE
Remove *.la files

### PR DESCRIPTION
**Pull request by scopatz**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by halldc** [comment]
@scopatz I think this PR causes [build failures](https://github.com/conda-forge/imagemagick-feedstock/pull/28) for the `imagemagick` package. Could you help me understand why these libtool files needed to be removed?

**Comment by scopatz** [comment]
@halldc - sure thing - you can read up on this in the tracking issue: https://github.com/conda-forge/conda-forge.github.io/issues/621

You can also follow the links there for more info

**Comment by scopatz** [comment]
basically, all of imagemagick's dependencies also need to remove the *la files.

**Comment by scopatz** [comment]
And there is a suggestion that conda-build should do this automatically, but no one has written the PR for that yet :wink:

**Comment by halldc** [comment]
@scopatz  Thanks for the explanation! This helped a lot

**Pull request merged**
